[project]
name = "gv"
version = "0.1.0"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.30",
  "requests>=2.32",
  "requests-cache>=1.2",
  "pydantic>=2.7",
  "python-dotenv>=1.0"
]

[tool.uvicorn]
host = "127.0.0.1"
port = 8000
reload = true
